-- MySQL Script generated by MySQL Workbench
-- 06/12/15 14:46:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table  `tip_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tip_korisnika` (
  `id_tip_korisnika` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(30) NOT NULL,
  `aktivan` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tip_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `status_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status_korisnika` (
  `id_status_korisnika` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(30) NOT NULL,
  `opis` VARCHAR(200) NULL,
  PRIMARY KEY (`id_status_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `korisnik` (
  `id_korisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(30) NOT NULL,
  `prezime` VARCHAR(30) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(20) NOT NULL,
  `zupanija` VARCHAR(30) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `datum_rodenja` DATE NOT NULL,
  `spol` CHAR(1) NOT NULL,
  `korisnicko_ime` VARCHAR(30) NOT NULL,
  `lozinka` VARCHAR(20) NOT NULL,
  `tip_korisnika_id_tip_korisnika` INT NOT NULL,
  `status_korisnika_id_status_korisnika` INT NOT NULL,
  PRIMARY KEY (`id_korisnik`),
  INDEX `fk_korisnik_tip_korisnika1_idx` (`tip_korisnika_id_tip_korisnika` ASC),
  INDEX `fk_korisnik_status_korisnika1_idx` (`status_korisnika_id_status_korisnika` ASC),
  CONSTRAINT `fk_korisnik_tip_korisnika1`
    FOREIGN KEY (`tip_korisnika_id_tip_korisnika`)
    REFERENCES `tip_korisnika` (`id_tip_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_status_korisnika1`
    FOREIGN KEY (`status_korisnika_id_status_korisnika`)
    REFERENCES `status_korisnika` (`id_status_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `dnevnik_rada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `dnevnik_rada` (
  `id_dnevnik_rada` INT NOT NULL AUTO_INCREMENT,
  `radnja` VARCHAR(80) NOT NULL,
  `vrijeme` DATETIME NOT NULL,
  `korisnik_id_korisnik` INT NOT NULL,
  `aktivan` TINYINT(1) NULL,
  PRIMARY KEY (`id_dnevnik_rada`),
  INDEX `fk_dnevnik_rada_korisnik_idx` (`korisnik_id_korisnik` ASC),
  CONSTRAINT `fk_dnevnik_rada_korisnik`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES  `korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `prodavac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `prodavac` (
  `id_prodavac` INT NOT NULL AUTO_INCREMENT,
  `korisnik_id_korisnik` INT NOT NULL,
  `automobil_id_automobil` INT NOT NULL,
  `aktivan` TINYINT(1) NULL,
  PRIMARY KEY (`id_prodavac`, `automobil_id_automobil`),
  INDEX `fk_prodavac_korisnik1_idx` (`korisnik_id_korisnik` ASC),
  CONSTRAINT `fk_prodavac_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES  `korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `sajam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `sajam` (
  `id_sajam` INT NOT NULL AUTO_INCREMENT,
  `lokacija` VARCHAR(50) NOT NULL,
  `pocetak` DATETIME NOT NULL,
  `kraj` DATETIME NOT NULL,
  `aktivan` TINYINT(1) NULL,
  PRIMARY KEY (`id_sajam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `sajam_has_prodavac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `sajam_has_prodavac` (
  `sajam_id_sajam` INT NOT NULL,
  `prodavac_id_prodavac` INT NOT NULL,
  PRIMARY KEY (`sajam_id_sajam`, `prodavac_id_prodavac`),
  INDEX `fk_sajam_has_prodavac_prodavac1_idx` (`prodavac_id_prodavac` ASC),
  INDEX `fk_sajam_has_prodavac_sajam1_idx` (`sajam_id_sajam` ASC),
  CONSTRAINT `fk_sajam_has_prodavac_sajam1`
    FOREIGN KEY (`sajam_id_sajam`)
    REFERENCES  `sajam` (`id_sajam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sajam_has_prodavac_prodavac1`
    FOREIGN KEY (`prodavac_id_prodavac`)
    REFERENCES  `prodavac` (`id_prodavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `automobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `automobil` (
  `id_automobil` INT NOT NULL AUTO_INCREMENT,
  `marka` VARCHAR(30) NOT NULL,
  `godiste` INT NOT NULL,
  `kilometraza` FLOAT NOT NULL,
  `snaga` FLOAT NOT NULL,
  `potrosnja` FLOAT NOT NULL,
  `tip_goriva` VARCHAR(30) NOT NULL,
  `dodatna_oprema` VARCHAR(200) NOT NULL,
  `pocetna_cijena` FLOAT NOT NULL,
  `zeljena_cijena` FLOAT NOT NULL,
  `ocjena` FLOAT NOT NULL,
  `kategorija_id_kategorija` INT ZEROFILL NOT NULL,
  `aktivan` TINYINT(1) NULL,
  PRIMARY KEY (`id_automobil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `tip_dokumenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `tip_dokumenta` (
  `id_tip_dokumenta` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `aktivan` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tip_dokumenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `galerija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `galerija` (
  `id_galerija` INT NOT NULL AUTO_INCREMENT,
  `naziv_dokumenta` VARCHAR(80) NOT NULL,
  `tip_dokumenta_id_tip_dokumenta` INT ZEROFILL NOT NULL,
  `aktivan` TINYINT(1) NULL,
  `automobil_id_automobil` INT NOT NULL,
  PRIMARY KEY (`id_galerija`, `automobil_id_automobil`),
  INDEX `fk_galerija_tip_dokumenta1_idx` (`tip_dokumenta_id_tip_dokumenta` ASC),
  INDEX `fk_galerija_automobil1_idx` (`automobil_id_automobil` ASC),
  CONSTRAINT `fk_galerija_tip_dokumenta1`
    FOREIGN KEY (`tip_dokumenta_id_tip_dokumenta`)
    REFERENCES  `tip_dokumenta` (`id_tip_dokumenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_galerija_automobil1`
    FOREIGN KEY (`automobil_id_automobil`)
    REFERENCES  `automobil` (`id_automobil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `korisnik_has_automobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `korisnik_has_automobil` (
  `korisnik_id_korisnik` INT NOT NULL,
  `automobil_id_automobil` INT NOT NULL,
  PRIMARY KEY (`korisnik_id_korisnik`, `automobil_id_automobil`),
  INDEX `fk_korisnik_has_automobil_automobil1_idx` (`automobil_id_automobil` ASC),
  INDEX `fk_korisnik_has_automobil_korisnik1_idx` (`korisnik_id_korisnik` ASC),
  CONSTRAINT `fk_korisnik_has_automobil_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES  `korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_has_automobil_automobil1`
    FOREIGN KEY (`automobil_id_automobil`)
    REFERENCES  `automobil` (`id_automobil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `sajam_has_korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `sajam_has_korisnik` (
  `sajam_id_sajam` INT NOT NULL,
  `korisnik_id_korisnik` INT NOT NULL,
  PRIMARY KEY (`sajam_id_sajam`, `korisnik_id_korisnik`),
  INDEX `fk_sajam_has_korisnik_korisnik1_idx` (`korisnik_id_korisnik` ASC),
  INDEX `fk_sajam_has_korisnik_sajam1_idx` (`sajam_id_sajam` ASC),
  CONSTRAINT `fk_sajam_has_korisnik_sajam1`
    FOREIGN KEY (`sajam_id_sajam`)
    REFERENCES  `sajam` (`id_sajam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sajam_has_korisnik_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES  `korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
