-- MySQL Script generated by MySQL Workbench
-- 06/11/15 00:32:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

INSERT INTO automobil VALUES (1, 'Audi' , 1993, 300, 90, 5.7, 'Diesel', 'ABS', 60000, 10000, 3.8, 1);

INSERT INTO sajam VALUES (1, 'Zagreb', '2015-05-05 08:00:00', '2015-05-08 23:00:00', 1);

INSERT INTO tip_korisnika VALUES (1, 'admin', 1);

INSERT INTO status_korisnika VALUES (1, 'aktivan', 'Aktivni registrirani korisnik');

INSERT INTO korisnik VALUES (1, 'admin', 'admin', 'Adminova 12', 'Adminsk', 'Adminska', 'admin@admin.hr', '2001-01-01', 'm', 'admin', 'admin', 1, 1);

INSERT INTO korisnik_has_automobil VALUES (1, 1);

INSERT INTO sajam_has_korisnik VALUES (1, 1);
